### ISSUE TITLE
Line Wrapping for Map Strings in the Developer GUI

### ISSUE THREAD

**Issue by AlexanderGroeger** [audinowho/PMDODump#9] opened 2022-01-14 20:00 UTC
**What's the issue?**
While editing the ground map strings through the developer GUI, the user may type in a string and associate a name to it; however sometimes strings may become excessively long which the use of the bottom scroll bar. This can become a cumbersome and tedious side task for the user as more text is added.

**Recommended Solution**
Allow rows in the map string table to vertically extend from text wrapping enabled in the _string_ column. This will provide a more natural look for large blocks of text.

**Comment by audinowho** [comment] 2022-01-24 02:40
PR has been merged.  Thanks for the contribution!

**Comment by audinowho** [comment] 2022-01-24 19:02
It looks like the Avalonia DataGrid is behaving differently from how it does in WPF.  The issue persists in spite of current changes so I am reopening this issue and adding known information:
https://stackoverflow.com/questions/4671836/how-get-a-wpf-datagrid-with-cells-that-wrap-text-instead-of-truncating-it

Currently this setting is in place for PMDO in its submodule repo.  It appears that the textblock in the datagrid is not following expected multiline behavior for wrapping.  This may need to be reported as an issue to AvaloniaUI's repo, but will likely need a minimal reproduction.

**Comment by AlexanderGroeger** [comment] 2023-05-04 21:11
Although this issue was reported on this repo, the Rogue Essence module repo has a [PR](https://github.com/AlexanderGroeger/RogueEssence/commit/7719e6a745031ee5602d16de0d7cd43adf804108) that needs review to close this issue.

**Comment by audinowho** [comment] 2023-05-28 03:06
https://github.com/RogueCollab/RogueEssence/pull/52

**Closed by audinowho** 2023-05-28 03:06 UTC
Labels: AvaloniaUI
