### ISSUE TITLE
I obtained a random error.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#92] opened 2022-05-15 11:29 UTC
Sorry for the title but i dunno what actually happened.
I was here:
![image](https://user-images.githubusercontent.com/6380147/168470420-744795b8-a7f3-4d29-8b0b-547a753aebd1.png)
and i decided to equip a X-ray specs and the game went "error"
[2022-05-15.zip](https://github.com/audinowho/PMDODump/files/8694822/2022-05-15.zip)
Edit: Taking out or equipping the item in any place also make the game to get errors, and does not matter if it's x-ray specs or for example an escape orb.
![image](https://user-images.githubusercontent.com/6380147/168470627-61e8c256-d555-49e1-a25d-d6e0afbababf.png)

**Comment by audinowho** [comment] 2022-05-15 15:16
duplicate of https://github.com/audinowho/PMDODump/issues/93

**Closed by audinowho** 2022-05-15 15:16 UTC
Labels: duplicate
